// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjkG1_3bYNqGCzKc54Gfj7srlJDr2DflE',
    appId: '1:603009514946:android:d7281e7293cfa4b56daa5b',
    messagingSenderId: '603009514946',
    projectId: 'taskmanager-fd334',
    storageBucket: 'taskmanager-fd334.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiBYf-xFV0eNXrf2x-2hJPshqMQpWnLLY',
    appId: '1:603009514946:ios:decf99484b2408026daa5b',
    messagingSenderId: '603009514946',
    projectId: 'taskmanager-fd334',
    storageBucket: 'taskmanager-fd334.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHxDQpArafQDojJP09VuqCXRcqG2CTIew',
    appId: '1:603009514946:web:74d61358b260b5b36daa5b',
    messagingSenderId: '603009514946',
    projectId: 'taskmanager-fd334',
    authDomain: 'taskmanager-fd334.firebaseapp.com',
    storageBucket: 'taskmanager-fd334.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHxDQpArafQDojJP09VuqCXRcqG2CTIew',
    appId: '1:603009514946:web:c604bcfc0b9b7d796daa5b',
    messagingSenderId: '603009514946',
    projectId: 'taskmanager-fd334',
    authDomain: 'taskmanager-fd334.firebaseapp.com',
    storageBucket: 'taskmanager-fd334.firebasestorage.app',
  );

}